### ISSUE TITLE
Two locations randomized to the same place

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#11]
Both the Goldenrod GTS entrance and the Whirl Islands NE entrance randomized to VICTORY_ROAD_3F_LADDER_DOWN_SE.  So if I entered victory road via the GTS and then tried to use the ladder I just came from, I ended up at Whirl Islands.

Also, this seed resulted in the 4th gym interior being locked behind the entrance to the Mahogany Town gym, which I believe is blocked until you finish all of the team rocket story in Mahogany.  Do you know whether it is even possible to do all of that prior to getting the fourth badge, and is that logic included in the randomizer?

[Attached log](https://github.com/adrienntindall/hgss-map-randomizer/files/8748762/SS.bugged.2.log)

**Comment by adrienntindall** [comment]
It's possible to do all the rocket stuff in Mahogany before the 4th badge, and if something gets locked behind that then you don't need the 4th badge/surf (if the logs contradict it, please tell me, since that would be a major issue I'd need to fix). 
The 2->1 warp issue is known and affects ~10% of seeds. I'm currently looking into how to fix it

**Comment by bsqrdminus4ac** [comment]
If it helps, I have run into this issue a couple more times, and every single time one of the affected warps is VICTORY_ROAD_3F_LADDER_DOWN_SE.

**Comment by adrienntindall** [comment]
Normally that would indicate that the logic lists the warp twice, but I can confirm that this is not the case. I've also seen it affect warps other than VICTORY_ROAD_3F_LADDER_DOWN_SE.
