### ISSUE TITLE
randomization not working

### ISSUE THREAD

**Issue by Arroki** [adrienntindall/hgss-map-randomizer#19]
So I have this issue where it keeps saying "PLAYER_HOUSE_TOP_ENT doesn't have a valid original PLAYER_HOUSE_TOP_EXIT is missing a definition for PLAYER_HOUSE_TOP_ENT" and "unbeatable seed. retrying..." and I tried to reinstall the radomizer and to use different roms but it still doesn't work.

**Comment by Arroki** [comment]
and also it only outputs the log file but not the actual randomized rom

**Comment by adrienntindall** [comment]
just be patient, it should work eventually, HGSS is just a huge game and lots can go wrong so alot of seeds are unbeatable
However, if it is closing before you see a message along the lines of "press any key to continue" then THAT is an issue.

**Comment by adrienntindall** [comment]
Also to be clear: randomization should only take a minute or two, if it's any longer than that then the .exe may be stuck in an infinite loop where it thinks all seeds are unbeatable

**Comment by Arroki** [comment]
that's basically what happens to me

**Comment by adrienntindall** [comment]
Alright Im gonna need more information to debug this since the randomizer is working fine for other people...
0) Did you download the source code or the release version
1) What version are you using/when did you download it if you don't remember
2) What version of the game are you trying to randomize
3) Did you drag and drop a newer version into the folder containing an old version (that would 100% break the logic) 
4) Do you see the "press any key to continue" button or does the program exit before that

**Comment by Arroki** [comment]
well it just worked but thanks for your help the problem I actually had was that i just put the zip file directly in the folder without extracting it
