### ISSUE TITLE
Impossible seed - cycling road behind house

### ISSUE THREAD

**Issue by Phyore** [adrienntindall/hgss-map-randomizer#27]
Gym 1 entrance is locked behind cycling road "house" (Where the guy says you need to be on a bike) but you cannot use a bike in that building and thus need to enter. However to get here you have to travel through MooMoo Farms building which takes you off of the bike.

Either a walk through walls or cycling anywhere is needed for this.

[4781 - Pokemon SoulSilver (U)(Xenophobia).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8877686/4781.-.Pokemon.SoulSilver.U.Xenophobia.nds_map_randomized.log)

**Comment by adrienntindall** [comment]
For whatever reason the solution to making this possible is going through the gate in Fuchsia from the outside and then going to the gate, since apparently there's a flag that gets set there to prevent you from dismounting when you're on the cycling road side of things. I'll look into fixing gf's poor coding but that's your workaround for the time being.
