### ISSUE TITLE
closed gym loop

### ISSUE THREAD

**Issue by wilson-joseph** [adrienntindall/hgss-map-randomizer#4]
GYM Internal door linked to dead-end building door (i am fairly sure)

mapping from log file
FUCHSIA_GYM_EXIT <-> BLACKTHORN_HOUSE_2_EXIT

p.s. sorry if this is not an issue and I've misunderstood the log file.
p.p.s really run, good work

**Comment by adrienntindall** [comment]
Which version of the randomizer were you using? One of the old versions had unclear log files since it defined what the warp became (here for instance, the Gym Exit became the new Blackthorn house 2 exit, which means it connects to the Blackthorn house's entrance)
Regardless, I was aware of a very very rare case that could cause closed loops and will fix it in the next version that I'm uploading later today.

**Comment by wilson-joseph** [comment]
version1.2. the latest one that you put on smallant's chat after the wrap fix (not the one nightbot one)

but I don't think I linked to blackthorn house as I did check it but started a new game now.

**Comment by adrienntindall** [comment]
Then yeah it looks like you hit the <1% chance that a closed-loop was generated, huge apologies there.

1.2.1 has addressed the issue and should only generate beatable seeds.
