### ISSUE TITLE
game freezes when in route 16 connecter

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#41]
Whenever I entered the Route 16 connecter, my game would freeze and not allow me to make any inputs
https://www.youtube.com/watch?v=jXwEWC5NRVQ (video link)

log file
[Pokemon - HeartGold Version (USA).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8996749/Pokemon.-.HeartGold.Version.USA.nds_map_randomized.log)

(the emulator allowed me to re-load save state if that is any information, just not any move-inputs)

**Comment by KrakenTheJaken** [comment]
I should also note that I am using the latest version of the randomizer with the files folder being downloaded from the last commit

**Comment by adrienntindall** [comment]
hmm I saw this issue in testing, but I fixed it and tested it to confirm it was fixed, which leads me to believe that I must've tested the route 18 gate twice
honestly couldn't tell you why it crashes there though since the only difference between the two was a single line that calls a function that stops the player from being able to swap between being on/off their bike (removed in r16 and set to the off state for r18)
Anyways it's fixed now and I'll push the update once I get the proper scripts built, thanks for bringing this to my attention
