### ISSUE TITLE
Dragon's den being wacky.

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#43]
After I beat Claire, I went to go into the dragon's den room but the "quiz" never activated.
Not sure what other info would be good since I don't have a video of me doing everything but here is the log file at least, and if you have any other questions I'll try to answer them.  (also using latest version of randomizer)
[Pokemon - HeartGold Version (USA).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9024792/Pokemon.-.HeartGold.Version.USA.nds_map_randomized.log)
t

**Comment by adrienntindall** [comment]
Hmm... that means that the flag to set that you got the badge somehow got set after you beat Clair. The only places where I set it beforehand to "fix" being able to get the badge early should've been 1) the player's house and 2) formerly when you get the running shoes, and then have the flag get un-set when Clair got defeated. Did you interact with any event (including talking to an NPC, etc) in either Cherrygrove or New Bark after you beat Clair? otherwise I'll likely have to do more research

**Comment by adrienntindall** [comment]
Also were you able to get the badge at all in either randomizer version 1.3.2 or 1.3.3? Basically need to know if this is a "sometimes the case" or "always the case" issue

**Comment by KrakenTheJaken** [comment]
I'm nearly certain that I did not interact with any other NPC's before getting the Claire badge. I can try doing another run tomorow to test if it is a 'always the case' issue.

**Comment by adrienntindall** [comment]
I'll test tonight, don't wanna waste your time on a known issue if I can work on it.
I think I might know what problem could be (aka something could've got fudged when I made Clair no longer able to wander from her gym) but won't be able to work on it for another hour or two

**Comment by adrienntindall** [comment]
Found the issue, uploaded as 1.3.3 again since it was literally 1 change lol
