### ISSUE TITLE
White 2 Strange House

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#45]
I'm testing White 2 right now and I'm noticing that there are multiple versions of the interior of Strange House (due to the furniture moving around) that are treated as separate maps. It's a bit of a headache to try to keep track of multiple variations of Strange House because the interiors are quite similar, as different variations can have the same door lead to different places (i.e. the exit in one variation leads to a route while the exit in another variation leads to a city). Are you planning on keeping it this way?

**Comment by adrienntindall** [comment]
I am planning on keeping it like this as is since there are easy ways to distinguish between them iirc, namely that phase 1 has nothing but the stairs unblocked, phase 2 has bottom floor rooms unblocked, and phase 3 has the top floor rooms unlocked. Keeping it this way means I can also randomize the Lunar Wing room, making Cresselia a bit more difficult to encounter, adding a bit more chaos to the run. If a "remove similar rooms" option is something people are interested in though, I'd be happy to add it to my backlog of things to be done
