### ISSUE TITLE
W2 First Gym Infinite Fresh Waters

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#50]
When I entered the room for Cheren's Gym, the event where the guide gives you a fresh water repeats forever, preventing any movement or interaction.

This was also with release 1.4.2.

**Comment by adrienntindall** [comment]
This is a known issue, but I've been unable to replicate it myself. Do you have any information about what you did earlier in the run that you think might affect it? Anything from interacting with a clearly modified event to doing things out of standard order/badge order or potentially even getting water from the guides in other gyms before might be helpful information towards figuring out why this occurs.

**Comment by bsqrdminus4ac** [comment]
Unfortunately, the first gym was literally the last key location I found in that file, so I could have tripped all sorts of other event flags by then.  I had not completed any of the later gyms yet at that point.  I also had not done the Alder / Floccesy Ranch story events that remove the kid from in front of the trainer school in Aspertia.  I did notice a rogue Cheren model inside a tree on Route 20 near the exit to Virbank - no clue what caused that.

I probably got a water from at least one other gym guide prior, since I know at least a couple automatically give you one as soon as you enter.

**Comment by adrienntindall** [comment]
Think I found the issue- Cheren leaves his gym during the main story from time to time, meaning his model isn't in the gym. The giving water thing is part of the same script as Cheren's introduction, but when the model isn't there to say anything, the script exits out. Since this is also before the variable that tells the game the event has already played out gets set, and since the player is on the trigger point, the event plays out over and over in the same loop.

That is all to say that now Cheren can't leave his gym, so the issue should be resolved when 1.4.6 comes out
